name: Semgrep
on: [pull_request]
jobs:
  pr_comment:
    name:  Testing PR Comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - run: |
          set +e
          python3 comment.py strict
          STRICT_EXIT_CODE=$?
      - if: ${{ $STRICT_EXIT_CODE==1 }}
        run: |
          echo "Hello"
      - if: ${{ $STRICT_EXIT_CODE==0 }}
        run: |
          echo "Hi"

  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      INPUT_PUBLISHURL: https://dev.semgrep.dev
    steps:
      - uses: actions/checkout@v1
      - uses: returntocorp/semgrep-action@v1
        # Optional environment variable for inline PR comments (beta)
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 61
