name: Semgrep
on: [pull_request]
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      INPUT_PUBLISHURL: https://dev.semgrep.dev
      SEMGREP_AGENT_DEBUG: 1
    steps:
      - uses: actions/checkout@v1
      - uses: returntocorp/semgrep-action/tests/local-image-action@adb6c1892fb3fdd4aff3d17ff1c7acda71a580a7
        # Optional environment variable for inline PR comments (beta)
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 61
          config: bad_config.yaml
