name: Semgrep
on: [pull_request]
jobs:
  pr_comment:
    name:  Testing PR Comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - run: |
          python3 comment.py ${{ secrets.GITHUB_TOKEN }} ${{ github.event.number }} $GITHUB_SHA

  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      INPUT_PUBLISHURL: https://dev.semgrep.dev
      SEMGREP_AGENT_DEBUG: 1
    steps:
      - uses: actions/checkout@v1
      - uses: returntocorp/semgrep-action@v1
        # Optional environment variable for inline PR comments (beta)
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 61
